### ISSUE TITLE
Sending message requires Select permission on table

### ISSUE THREAD

**Issue by jontelarsson94** [NServiceBusExtensions/NServiceBus.SqlNative#220]
Sending a message in NServiceBus usually only requires insert permissions on the queue but in this case it requires both insert and select permissions. This is because the sql for sending a message uses this line:

"output inserted.RowVersion"

Since the receiver might not want the sender to be able to read the messages, this should be fixed.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron](https://github.com/NServiceBusExtensions/Home/#licensingpatron-faq). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by SimonCropp** [comment]
happy to take a pull request for this if you ever get around to fixing it
